<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="172.6330" tests="12" failures="2">
  <testsuite name="Root Suite" timestamp="2022-01-13T13:25:59" tests="0" file="cypress/integration/avt_operations/all_flows.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Download Demo" timestamp="2022-01-13T13:25:59" tests="12" time="172.6220" failures="2">
    <testcase name="Download Demo Visit AVT site." time="2.0870" classname="Visit AVT site.">
    </testcase>
    <testcase name="Download Demo Sign In" time="2.8180" classname="Sign In">
    </testcase>
    <testcase name="Download Demo Add dialogues" time="6.4680" classname="Add dialogues">
    </testcase>
    <testcase name="Download Demo Play dialogue" time="1.7740" classname="Play dialogue">
    </testcase>
    <testcase name="Download Demo Delete Created Avatars (If already exists)" time="5.3000" classname="Delete Created Avatars (If already exists)">
    </testcase>
    <testcase name="Download Demo Create 1st Avatar" time="6.4490" classname="Create 1st Avatar">
    </testcase>
    <testcase name="Download Demo Create 2nd Avatar" time="7.3780" classname="Create 2nd Avatar">
    </testcase>
    <testcase name="Download Demo Verify if both avatars are created" time="3.0360" classname="Verify if both avatars are created">
    </testcase>
    <testcase name="Download Demo Create New Scenario" time="12.9380" classname="Create New Scenario">
    </testcase>
    <testcase name="Download Demo Go back to Home Page" time="5.2360" classname="Go back to Home Page">
    </testcase>
    <testcase name="Download Demo Create video for avatar dialogues" time="0.0000" classname="Create video for avatar dialogues">
      <failure message="`cy.screenshot()` timed out waiting `30000ms` to complete." type="CypressError"><![CDATA[CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
    at https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:159546:81
    at tryCatcher (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:13196:23)
    at https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:8318:41
    at tryCatcher (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:13196:23)
    at Promise._settlePromiseFromHandler (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:11131:31)
    at Promise._settlePromise (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:11188:18)
    at Promise._settlePromise0 (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:11233:10)
    at Promise._settlePromises (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:11309:18)
    at _drainQueueStep (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:7903:12)
    at _drainQueue (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:7896:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:7912:5)
    at Async.drainQueues (https://avt-test.azurewebsites.net/__cypress/runner/cypress_runner.js:7782:14)]]></failure>
    </testcase>
    <testcase name="Download Demo Save and Download Dialogue" time="0.0000" classname="Save and Download Dialogue">
      <failure message="The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  &gt; Cannot set properties of null (setting &apos;frames&apos;)

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application" type="TypeError"><![CDATA[TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot set properties of null (setting 'frames')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
    at https://avt-test.azurewebsites.net/static/js/main.53867e39.chunk.js:1:41135
    at u (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:989436)
    at Generator._invoke (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:989224)
    at Generator.next (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:989861)
    at r (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:4203)
    at l (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:4406)
    at https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:4465
    at new Promise (<anonymous>)
    at n.saveScenarioInNewFormat (https://avt-test.azurewebsites.net/static/js/2.4bfab1a9.chunk.js:2:4346)
    at n.a.handleGenerateTalkFile (https://avt-test.azurewebsites.net/static/js/main.53867e39.chunk.js:1:43713)]]></failure>
    </testcase>
  </testsuite>
</testsuites>